### ISSUE TITLE
Mac OS X build issue

### ISSUE THREAD

**Issue by ryanliue** [acpica/acpica#155]
../../../source/os_specific/service_layers/osunixxf.c:832:42: error: 'tmpnam' is
      deprecated: This function is provided for compatibility reasons only. Due
      to security concerns inherent in the design of tmpnam(3), it is highly
      recommended that you use mkstemp(3) instead.
      [-Werror,-Wdeprecated-declarations]
        char            *SemaphoreName = tmpnam (NULL);
                                         ^
/usr/include/stdio.h:276:7: note: 'tmpnam' has been explicitly marked deprecated
      here
char    *tmpnam(char *);
         ^
../../../source/os_specific/service_layers/osunixxf.c:885:9: error: 'sem_close'
      is deprecated [-Werror,-Wdeprecated-declarations]
    if (sem_destroy (Sem) == -1)
        ^
../../../source/include/platform/acmacosx.h:122:29: note: expanded from macro
      'sem_destroy'
# define sem_destroy         sem_close

```
                        ^
```

/usr/include/sys/semaphore.h:53:5: note: 'sem_close' has been explicitly marked
      deprecated here
int sem_destroy(sem_t *) __deprecated;
    ^
../../../source/include/platform/acmacosx.h:122:29: note: expanded from macro
      'sem_destroy'
# define sem_destroy         sem_close

```
                        ^
```

2 errors generated.
make[1]: **\* [obj/osunixxf.o] Error 1
make: **\* [acpiexec] Error 2

**Comment by acpibob** [comment]
perhaps OS X will require its own service layer (instead of osunixxf.c).

**Comment by zetalog** [comment]
Subject: [PATCH] MacOSX: Fix build issue caused by deprecated functions

The following build errors can be seen for MacOSX builds:
.../osunixxf.c:829:42: error: 'tmpnam' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of tmpnam(3), it is highly recommended that you use mkstemp(3) instead. [-Werror,-Wdeprecated-declarations]
.../osunixxf.c:882:9: error: 'sem_close' is deprecated [-Werror,-Wdeprecated-declarations]
.../acmacosx.h:122:29: note: expanded from macro 'sem_destroy'
#define sem_destroy         sem_close

tmpnam() should NOT be used and provides an easy and obvious priviledge attack point.
This patch fixes it with mktemp().

sem_destroy() issue is caused by the wrong order of the following lines:
  #define #sem_destroy        sem_close
  #include <semaphore.h>
This patch fixes it by removing the buggy re-definitiion. Lv Zheng.
---
 source/include/platform/acmacosx.h           | 1 -
 source/os_specific/service_layers/osunixxf.c | 9 ++++++++-
 2 files changed, 8 insertions(+), 2 deletions(-)

diff --git a/source/include/platform/acmacosx.h b/source/include/platform/acmacosx.h
index f5d2ce3..89a23fe 100644
--- a/source/include/platform/acmacosx.h
+++ b/source/include/platform/acmacosx.h
@@ -119,7 +119,6 @@
 #include "aclinux.h"
 
 #ifdef __APPLE__
-#define sem_destroy         sem_close
 #define ACPI_USE_ALTERNATE_TIMEOUT
 #endif /* __APPLE__ */
 
diff --git a/source/os_specific/service_layers/osunixxf.c b/source/os_specific/service_layers/osunixxf.c
index f04b59e..cf7931b 100644
--- a/source/os_specific/service_layers/osunixxf.c
+++ b/source/os_specific/service_layers/osunixxf.c
@@ -826,7 +826,7 @@ AcpiOsCreateSemaphore (
 
 #ifdef __APPLE__
     {
-        char            *SemaphoreName = tmpnam (NULL);
+        char            *SemaphoreName = mktemp (NULL);
 
         Sem = sem_open (SemaphoreName, O_EXCL|O_CREAT, 0755, InitialUnits);
         if (!Sem)
@@ -879,10 +879,17 @@ AcpiOsDeleteSemaphore (
         return (AE_BAD_PARAMETER);
     }
 
+#ifdef __APPLE__
+    if (sem_close (Sem) == -1)
+    {
+        return (AE_BAD_PARAMETER);
+    }
+#else
     if (sem_destroy (Sem) == -1)
     {
         return (AE_BAD_PARAMETER);
     }
+#endif
 
     return (AE_OK);
 }
-- 
2.3.2 (Apple Git-55)

**Comment by acpibob** [comment]
Do the changes above fix the issue?

**Comment by zetalog** [comment]
Hi,

Please try this pull request:
https://github.com/acpica/acpica/pull/176

Thanks

**Comment by YK2** [comment]
hey there this patch does fix the build process, but when i run the created created binary it exits with a segmentation fault 11, i can't help but wander if sem_destroy and sem_close are not allowed to run on mac OS X, i am using yosemite 10.10.5 to compile btw.

i am pretty sure i also noticed some warnings flying by about unused name or address or reference (something like that anyway) but when i go back through the terminal output, there are no errors.

i will rebuild again and try and see if i can catch them

**Comment by YK2** [comment]
here is the invisible error or warning, i managed to find it, i am not sure this relates to the segmentation fault or not.

[invisible build error.txt](https://github.com/acpica/acpica/files/487258/invisible.build.error.txt)
[acpiexec segmentation fault 11.mov.zip](https://github.com/acpica/acpica/files/487264/acpiexec.segmentation.fault.11.mov.zip)

**Comment by Ambush80** [comment]
i forgot you might not wanna download that
this is the invisible build error that i can’t seem to find in terminal once the compile has finished


m4 -P -I../../../source/compiler ../../../source/compiler/aslparser.y > obj/aslcompiler.y
_d=`mktemp -d obj/AslCompiler.XXXXXX` && cd $_d && bison -y -v -d -pAslCompiler /Users/Ambush/Desktop/acpica-unix-20160831/generate/unix/iasl/obj/aslcompiler.y && cd - && mv $_d/y.tab.h obj/aslcompiler.y.h; _r=$?; rm -fr $_d; exit $_r
/Users/Ambush/Desktop/acpica-unix-20160831/generate/unix/iasl/obj/aslcompiler.y:2157.7-2164.53: warning: unused value: $15
/Users/Ambush/Desktop/acpica-unix-20160831/generate/unix/iasl
flex -i -s -PAslCompiler -oobj/aslcompilerlex.c ../../../source/compiler/aslcompiler.l
_d=`mktemp -d obj/AslCompiler.XXXXXX` && cd $_d && bison -y -v -d -pAslCompiler /Users/Ambush/Desktop/acpica-unix-20160831/generate/unix/iasl/obj/aslcompiler.y && cd - && mv $_d/y.tab.c obj/aslcompilerparse.c; _r=$?; rm -fr $_d; exit $_r
/Users/Ambush/Desktop/acpica-unix-20160831/generate/unix/iasl/obj/aslcompiler.y:2157.7-2164.53: warning: unused value: $15
/Users/Ambush/Desktop/acpica-unix-20160831/generate/unix/iasl
_d=`mktemp -d obj/DtParser.XXXXXX` && cd $_d && bison -y -v -d -pDtParser /Users/Ambush/Desktop/acpica-unix-20160831/source/compiler/dtparser.y && cd - && mv $_d/y.tab.h obj/dtparser.y.h; _r=$?; rm -fr $_d; exit $_r
/Users/Ambush/Desktop/acpica-unix-20160831/generate/unix/iasl
flex -i -s -PDtParser -oobj/dtparserlex.c ../../../source/compiler/dtparser.l
_d=`mktemp -d obj/DtParser.XXXXXX` && cd $_d && bison -y -v -d -pDtParser /Users/Ambush/Desktop/acpica-unix-20160831/source/compiler/dtparser.y && cd - && mv $_d/y.tab.c obj/dtparserparse.c; _r=$?; rm -fr $_d; exit $_r
/Users/Ambush/Desktop/acpica-unix-20160831/generate/unix/iasl
_d=`mktemp -d obj/PrParser.XXXXXX` && cd $_d && bison -y -v -d -pPrParser /Users/Ambush/Desktop/acpica-unix-20160831/source/compiler/prparser.y && cd - && mv $_d/y.tab.h obj/prparser.y.h; _r=$?; rm -fr $_d; exit $_r
/Users/Ambush/Desktop/acpica-unix-20160831/generate/unix/iasl
flex -i -s -PPrParser -oobj/prparserlex.c ../../../source/compiler/prparser.l
_d=`mktemp -d obj/PrParser.XXXXXX` && cd $_d && bison -y -v -d -pPrParser /Users/Ambush/Desktop/acpica-unix-20160831/source/compiler/prparser.y && cd - && mv $_d/y.tab.c obj/prparserparse.c; _r=$?; rm -fr $_d; exit $_r
/Users/Ambush/Desktop/acpica-unix-20160831/generate/unix/iasl

**Comment by zetalog** [comment]
Do you mean this: warning: unused value: $15
we can see it on other platforms.
Please ignore.

However, the segfault need to be fixed.
I'll check this issue.

**Comment by Ambush80** [comment]
nice !, i am gonna build this in windows as well and see what happens, i will let you know if it throws a similar error

**Comment by Ambush80** [comment]
i think windows builds fine as does the merged fix, one package on win didn't build but i found out that was due to a known windows bug, have you had any luck tracking down the OS X segfault cause ?

**Comment by zetalog** [comment]
I haven't started the OSX segfault case.
I guess it is related to termios.

I'm still working on testing my recent locking changes.
I'll borrow an OSX machine from my colleague and start this then.

Thanks

**Comment by zetalog** [comment]
https://github.com/acpica/acpica/pull/179

**Comment by zetalog** [comment]
Have you checked upstream ACPICA?
Shall we close this now?

**Comment by acpibob** [comment]
Any news on this?

**Comment by acpibob** [comment]
closing
