### ISSUE TITLE
Compile error, missing termio.h OS X

### ISSUE THREAD

**Issue by STLVNUB** [acpica/acpica#18]
Hi, you need to change termio.h to termios.h for OS X

**Comment by acpibob** [comment]
This issue appears to have been resolved.

**Comment by STLVNUB** [comment]
Where is it resolved??

**Comment by acpibob** [comment]
As per comment above, ACPICA is no longer using termio.h

OK, I see that there is another issue. I'm not sure that we can use mkstemp because of portability concerns.

**Comment by acpibob** [comment]
tmpnam is used only under this:
#ifdef __APPLE__

**Comment by YK2** [comment]
hi there, i am not a coder but i am running into the same problem when compiling on mac OS X yosemite:
#ifdef __APPLE__
    {
        char            *SemaphoreName = tmpnam (NULL);
Due to security concerns inherent in the design of tmpnam(3), it is highly
      recommended that you use mkstemp(3) instead. [-Werror,-Wdeprecated-declarations]

so i change to
char            *SemaphoreName = mktemp (NULL); 
or 
char            *SemaphoreName = mkdtemp (NULL);
problem goes away, then : error: 'sem_close' is deprecated
if (sem_destroy (Sem) == -1)
        ^

so i change to

if (sem_unlink (Sem) == -1)  (this should work it is the recommended way of doing it)

problem is still here

i have tried a few other methods i found online to get around it but nothing i do seems to work.

do you have any idea how i can fix it or is it something that you can fix ?

**Comment by zetalog** [comment]
STLVNUB:
Have you tried https://github.com/acpica/acpica/pull/176?

acpibob & juikim:
Do we need to improve ACPICA around termios.h?

**Comment by zetalog** [comment]
> OK, I see that there is another issue. I'm not sure that we can use mkstemp because of portability concerns.
There is no easy way to use anonymous mutex on APPLE platforms.
Other programs will use an increasing ID to create mutex which still have problems if the ID expires.
So IMO we can use the solution now.
We don't mean to provide a perfect solution for APPLE, and there is no perfect solution for this issue.
We just want our simple console programs to be compiled, to work for a short period.

Thanks
