### ISSUE TITLE
STAO table question

### ISSUE THREAD

**Issue by Xc2333** [acpica/acpica#459]
Sorry to bother you, but I have a question that the STAO table can be used only in a virtual machine environment? ( I made a STAO table but doesn't work for real OS)

**Comment by SchmErik** [comment]
From reading the spec https://wiki.xenproject.org/images/0/02/Status-override-table.pdf it looks like this table is meant for a vm environment.

I guess it really depends on the OS. For example, a quick glance in the linux source make it seems that linux support is limited. Not all operating systems may support STAO.

What are you trying to accomplish?

**Comment by Xc2333** [comment]
Yes，i have read that Linux document before，so why  i  have a question about this.

What i want to do is to ignore some device in dsdt for macOS，emm，according to what you said ，it seems that macOS 
does not support SATO table。

Anyway，thanks for reply！

**Comment by acpibob** [comment]
Depends on what you mean by “support”. True, iASL does not support SATO (I’m not even sure what it is) in iASL for compilation/disassembly, but the kernel-level ACPICA should automatically support it in the sense that if a driver asks for it, and it is present, ACPICA will return it to the driver.

**Comment by Xc2333** [comment]
iASL can compile the STAO。
So support or not depends on the needs of the system，I think I figured it out，thank you！

**Comment by SchmErik** [comment]
closing

**Comment by ahs3** [comment]
Sorry to be late to the party... I was one of those responsible for adding this table to the spec.

The STAO was specifically designed for use by Xen, so yes, for a virtual environment.  The table definition and maintenance of the definition belongs solely to Xen for now.  This is one of the class of tables that the spec references, ACPICA needs to parse, but is maintained by organizations outside of the UEFI ACPI Spec Working Group.

So, in theory, there should not be any use of this table outside a Xen environment.  The hypervisor itself (i.e., dom0) creates the table and passes it to guests (domU) in order to designate devices that are not to be used/shared, even if discovered by an OS, which does require the OS to know about the STAO.

**Comment by Xc2333** [comment]
> Sorry to be late to the party... I was one of those responsible for adding this table to the spec.
> 
> The STAO was specifically designed for use by Xen, so yes, for a virtual environment. The table definition and maintenance of the definition belongs solely to Xen for now. This is one of the class of tables that the spec references, ACPICA needs to parse, but is maintained by organizations outside of the UEFI ACPI Spec Working Group.
> 
> So, in theory, there should not be any use of this table outside a Xen environment. The hypervisor itself (i.e., dom0) creates the table and passes it to guests (domU) in order to designate devices that are not to be used/shared, even if discovered by an OS, which does require the OS to know about the STAO.

Ok, I understand, thank you for your explanation.

STAO is useful, but it is a pity to not support an environment other than Xen. Anyway, thank you for all your contributions to acpica.
