### ISSUE TITLE
acpinames.exe can't build successfully 

### ISSUE THREAD

**Issue by shaopy** [acpica/acpica#599]
use VS2010 try to build  latest code,  found that acpinames.exe can't build successfully with default config,
error message :

![image](https://user-images.githubusercontent.com/7878575/80448840-2509a700-8950-11ea-990c-41315e7d9404.png)

if I add  related source files to the acpinames solution from Explorer view, will get more and more errors, list all related source files here:

![image](https://user-images.githubusercontent.com/7878575/80449042-a95c2a00-8950-11ea-912f-7403487010c3.png)

**Comment by SchmErik** [comment]
please try using the solution file in msvc2017
@acpibob should we consider removing the msvc9 files?

**Comment by shaopy** [comment]
Yes, use MSVC2017 can build pass , what is the differences  between two ones ?

**Comment by acpibob** [comment]
I’m not sure what is going on here. I can successfully generate acpinames with both MSVC 2017 and by using the default makefile for the utility (on Cygwin).

BTW, we are considering removing Acpinames since it was simply intended to show how ACPICA can be used component-wise to build new utilities. Otherwise, the functionality is already covered by Acpiexec (by using the namespace command).

**Comment by acpibob** [comment]
Yes, we should remove the msvc9 files at this point.

I’m considering removing “AcpiNames” entirely – since it doesn’t contain the interpreter, it cannot execute module-level code. In any case, the function of AcpiNames is duplicated in AcpiExec.

**Comment by acpibob** [comment]
We no longer maintain the project files under msvc9.

**Comment by SchmErik** [comment]
we no longer maintain this tool and we have removed all source files and build files associated with this tool. Closing
