### ISSUE TITLE
Return path warnings

### ISSUE THREAD

**Issue by vit9696** [acpica/acpica#653]
Consider the following `_INI` code:

```
DefinitionBlock("", "SSDT", 2, "ACDT", "PNLF", 0)
{
    Device(TEST)
    {
        Name(_ADR, Zero)
        Method(_INI)
        {
            Local4 = 1
            If (!(1 & Local4)) { Return() }
        }
    }
}
```

This code compiles without any warnings with the latest iasl. However, after the decompilation of the compiled code the following code is generated:

```
DefinitionBlock ("", "SSDT", 2, "ACDT", "PNLF", 0x00000000)
{
    Device (TEST)
    {
        Name (_ADR, Zero)  // _ADR: Address
        Method (_INI, 0, NotSerialized)  // _INI: Initialize
        {
            Local4 = One
            If (!(One & Local4))
            {
                Return (Zero)
            }
        }
    }
}
```

This code produces a warning: `6, 3115, Not all control paths return a value (\TEST._INI)`. While according to `19.6.118 Return (Return from Method Execution)` of the ACPI 6.3 specification `Return` without a value is compiled into `Return(Zero)`, I believe it is idiomatic to use `Return()` for methods to early return a method not returning a value (like `_INI`).

This is a regression, as in the past (iasl 20200925) the code decompiled to `Return ()` and thus produced no issue. I suggest to take one of the three routes:

- Decompile the `Return (Zero)` opcodes to `Return ()` just as before.
- Disable the `Not all control paths return a value` warning for `Return(Zero)`.
- Make `Return()` also produce a `Not all control paths return a value` warning.

**Comment by SchmErik** [comment]
> This code produces a warning: `6, 3115, Not all control paths return a value (\TEST._INI)`. While according to `19.6.118 Return (Return from Method Execution)` of the ACPI 6.3 specification `Return` without a value is compiled into `Return(Zero)`, I believe it is idiomatic to use `Return()` for methods to early return a method not returning a value (like `_INI`).
> 
> This is a regression, as in the past (iasl 20200925) the code decompiled to `Return ()` and thus produced no issue. I suggest to take one of the three routes:


It looks like 20200925 disassembles to Return(Zero) as well. Could you help us track down the version number that caused this?.. This bug may have existed this entire time...

**Comment by vit9696** [comment]
Actually I think I was wrong about the regression part, it may have been for quite some time like this indeed if not from the beginning.

**Comment by SchmErik** [comment]
Ok thanks for the report. I'm thinking either option 1 or 2 is a good. Bob is out this week but I'll consult with him after he gets back before making the change.

**Comment by acpibob** [comment]
I agree, this issue has probably been around “forever”.

I prefer option 2.
Bob

**Comment by acpibob** [comment]
I'm thinking what we will do is simply disable the warning for Return(Zero).

**Comment by SchmErik** [comment]
Bob and I talked about this over several conversations and we came to the conclusion that this is probably best left alone in this current state. Return() and Return(0) are represented in the same way in AML byte code. For the disassembler to emit the correct one, we need to understand the return type of the control method. The return type information is not contained inside of AML. In other words, the return type disappears in compilation so it's impossible for the interpreter to emit a Return(Zero) or Return() for an arbitrary method. We don't want to disable the "not all control paths return a value" because this is useful in detecting places where someone forgot to write a return statement. Making return() produce this warning may confuse programmers and have them insert Return() where it may not be needed. We think that "not all control paths return a value" warning is a valuable warning and suppressing this will cause more harm. Disassembly is typically used in cases where people are trying to diagnose issues so we are ok having iASL emit a warning for the case that you've shown. Although this is a warning, the warning itself will not prevent the compiler from generating .aml so that users who are trying to debug/troubleshoot can proceed with their activities. I hope this makes sense. I'm going to close this but feel free to let us know if you have any questions.

Thanks. Closing.
