### ISSUE TITLE
table compiler cannot recompile table it just disassembled if it has a zero-length Unicode string

### ISSUE THREAD

**Issue by ahs3** [acpica/acpica#703]
Please find attached a WPBT that has a zero-length command line Unicode string; the actual creator of this table has been hidden, but this comes from an existing platform, compiled by a tool other than iASL.  The table disassembles with iASL just fine (foo->aml ->foo.dsl).  But, the resulting text cannot be recompiled back into binary (foo.dsl->foo.aml) due to the zero-length string; the field name is present, but there is no value, just a comment.

I started thinking about ways to fix this but then realized it's not clear to me what the correct behavior should be: are zero length Unicode strings even allowed in iASL?  If so, then handling them needs to be changed (empty field values need to be possible).  If not, then there needs to be error reporting.

So, what's the correct behavior?  Can this be fixed?

[foo.zip](https://github.com/acpica/acpica/files/6756086/foo.zip)

**Comment by acpibob** [comment]
I’m not sure what the correct behavior is supposed to be – I’ll need to look at the definition of WPBT.


From: Al Stone ***@***.***>
Sent: Friday, July 02, 2021 10:21 AM
To: acpica/acpica ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [acpica/acpica] table compiler cannot recompile table it just disassembled if it has a zero-length Unicode string (#703)


Please find attached a WPBT that has a zero-length command line Unicode string; the actual creator of this table has been hidden, but this comes from an existing platform, compiled by a tool other than iASL. The table disassembles with iASL just fine (foo->aml ->foo.dsl). But, the resulting text cannot be recompiled back into binary (foo.dsl->foo.aml) due to the zero-length string; the field name is present, but there is no value, just a comment.

I started thinking about ways to fix this but then realized it's not clear to me what the correct behavior should be: are zero length Unicode strings even allowed in iASL? If so, then handling them needs to be changed (empty field values need to be possible). If not, then there needs to be error reporting.

So, what's the correct behavior? Can this be fixed?

foo.zip<https://github.com/acpica/acpica/files/6756086/foo.zip>

**Comment by acpibob** [comment]
As far as I can tell, the WPBT attached as aml does not have a zero-length command line Unicode string:

    0030: 01 01 06 00 30 00 30 00 00 00                    // ....0.0...
[030h 0048   1]                       Layout : 01
[031h 0049   1]                         Type : 01
[032h 0050   2]             Arguments Length : 0006
[000h 0000   6]       Command-line Arguments : "00"

In this case, the Unicode string is represented by:

30 00 30 00 00 00    /* Includes the NULL terminator */

The code to compile this table with the Unicode string does in fact already exist.

In any case, the code to dump the Unicode string simply did not exist. I have this working now.
Bob


From: Moore, Robert
Sent: Wednesday, July 07, 2021 12:08 PM
To: acpica/acpica ***@***.***>; acpica/acpica ***@***.***>
Cc: Subscribed ***@***.***>
Subject: RE: [acpica/acpica] table compiler cannot recompile table it just disassembled if it has a zero-length Unicode string (#703)

I’m not sure what the correct behavior is supposed to be – I’ll need to look at the definition of WPBT.


From: Al Stone ***@***.******@***.***>>
Sent: Friday, July 02, 2021 10:21 AM
To: acpica/acpica ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: [acpica/acpica] table compiler cannot recompile table it just disassembled if it has a zero-length Unicode string (#703)


Please find attached a WPBT that has a zero-length command line Unicode string; the actual creator of this table has been hidden, but this comes from an existing platform, compiled by a tool other than iASL. The table disassembles with iASL just fine (foo->aml ->foo.dsl). But, the resulting text cannot be recompiled back into binary (foo.dsl->foo.aml) due to the zero-length string; the field name is present, but there is no value, just a comment.

I started thinking about ways to fix this but then realized it's not clear to me what the correct behavior should be: are zero length Unicode strings even allowed in iASL? If so, then handling them needs to be changed (empty field values need to be possible). If not, then there needs to be error reporting.

So, what's the correct behavior? Can this be fixed?

foo.zip<https://github.com/acpica/acpica/files/6756086/foo.zip>

**Comment by acpibob** [comment]
As far as I can tell, the WPBT attached as aml does not have a zero-length command line Unicode string:

    0030: 01 01 06 00 30 00 30 00 00 00                    // ....0.0...
[030h 0048   1]                       Layout : 01
[031h 0049   1]                         Type : 01
[032h 0050   2]             Arguments Length : 0006
[000h 0000   6]       Command-line Arguments : "00"

In this case, the Unicode string is represented by:

30 00 30 00 00 00    /* Includes the NULL terminator */

The code to compile this table with the Unicode string does in fact already exist.

In any case, the code to dump the Unicode string simply did not exist. I have this working now.
Bob




From: Al Stone ***@***.***>
Sent: Friday, July 02, 2021 10:21 AM
To: acpica/acpica ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [acpica/acpica] table compiler cannot recompile table it just disassembled if it has a zero-length Unicode string (#703)


Please find attached a WPBT that has a zero-length command line Unicode string; the actual creator of this table has been hidden, but this comes from an existing platform, compiled by a tool other than iASL. The table disassembles with iASL just fine (foo->aml ->foo.dsl). But, the resulting text cannot be recompiled back into binary (foo.dsl->foo.aml) due to the zero-length string; the field name is present, but there is no value, just a comment.

I started thinking about ways to fix this but then realized it's not clear to me what the correct behavior should be: are zero length Unicode strings even allowed in iASL? If so, then handling them needs to be changed (empty field values need to be possible). If not, then there needs to be error reporting.

So, what's the correct behavior? Can this be fixed?

foo.zip<https://github.com/acpica/acpica/files/6756086/foo.zip>

**Comment by ahs3** [comment]
Argh. My bad.  I copied the wrong ASL file.

The line in the actual ASL looks like this (nothing after the ':'):

[000h 0000   6]       Command-line Arguments :

**Comment by acpibob** [comment]
What about the AML file in the zip file?

**Comment by acpibob** [comment]
This is what I see from the current compiler (V20210604) from disassembling the .AML file you sent:

[024h 0036   4]                 Handoff Size : 000D6308
[028h 0040   8]              Handoff Address : 00000000CAB57000
[030h 0048   1]                       Layout : 01
[031h 0049   1]                         Type : 01
[032h 0050   2]             Arguments Length : 0006
/**** ACPI subtable terminates early (Len 6) - may be older version (dump table) */

This is the fixed version of iASL (with an AML with an actual zero-length Unicode string:

[024h 0036   4]                 Handoff Size : 000D6308
[028h 0040   8]              Handoff Address : 00000000CAB57000
[030h 0048   1]                       Layout : 01
[031h 0049   1]                         Type : 01
[032h 0050   2]             Arguments Length : 0000

Raw Table Data: Length 52 (0x34)


From: Moore, Robert
Sent: Friday, July 09, 2021 1:09 PM
To: acpica/acpica ***@***.***>
Subject: RE: [acpica/acpica] table compiler cannot recompile table it just disassembled if it has a zero-length Unicode string (#703)

What about the AML file in the zip file?

**Comment by ahs3** [comment]
Whups.  Really messed that up.  Please find the proper foo.zip.
[foo.zip](https://github.com/acpica/acpica/files/6811227/foo.zip)

**Comment by acpibob** [comment]
OK, I’ve got this fixed. I can send you a patch, or the windows binary for the compiler.

**Comment by ahs3** [comment]
A copy of the patch would be quite nice.  Thanks.

**Comment by acpibob** [comment]
Here’s the patch. Note, it is against the native ACPICA format, not the “Linuxized” version.

**Comment by acpibob** [comment]
I don't know how to attach a file to a github email, I'll need your email address.

**Comment by ahs3** [comment]
Got the patch and it seems to work well.  Thanks!  This will show up in the next release, yeah?

**Comment by acpibob** [comment]
Yes, it will be released this Friday.

**Comment by acpibob** [comment]
Released in version 20210730. Closing.
