### ISSUE TITLE
build acpiexec failed with gcc-12

### ISSUE THREAD

**Issue by yetist** [acpica/acpica#771]
The error log:
```
obj/acpiexec ../../../source/components/utilities/utdebug.c
../../../source/components/utilities/utdebug.c: In function 'AcpiUtInitStackPtrTrace':
../../../source/components/utilities/utdebug.c:188:31: error: storing the address of local variable 'CurrentSp' in 'AcpiGbl_EntryStackPointer' [-Werror=dangling-pointer=]
  188 |     AcpiGbl_EntryStackPointer = &CurrentSp;
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
../../../source/components/utilities/utdebug.c:185:29: note: 'CurrentSp' declared here
  185 |     ACPI_SIZE               CurrentSp;
      |                             ^~~~~~~~~
```

**Comment by acpibob** [comment]
We do this in order to measure stack usage by ACPICA.  Any ideas on how to do this differently?

Thanks,
Bob


From: Wu Xiaotian ***@***.***>
Sent: Thursday, April 28, 2022 4:21 AM
To: acpica/acpica ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [acpica/acpica] build acpiexec failed with gcc-12 (Issue #771)


The error log:

obj/acpiexec ../../../source/components/utilities/utdebug.c

../../../source/components/utilities/utdebug.c: In function 'AcpiUtInitStackPtrTrace':

../../../source/components/utilities/utdebug.c:188:31: error: storing the address of local variable 'CurrentSp' in 'AcpiGbl_EntryStackPointer' [-Werror=dangling-pointer=]

  188 |     AcpiGbl_EntryStackPointer = &CurrentSp;

      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~

../../../source/components/utilities/utdebug.c:185:29: note: 'CurrentSp' declared here

  185 |     ACPI_SIZE               CurrentSp;

      |                             ^~~~~~~~~

**Comment by acpibob** [comment]
Are you saying that simply making CurrentSp to be static solves the issue?

**Comment by acpibob** [comment]
So, I don't understand why declaring CurrentSp "static" makes any difference to the compiler.

**Comment by acpibob** [comment]
It appears that the "static" keyword puts the variable into the data segment, not the stack. Thus, taking a pointer into the data segment does not give us the value that we want.

**Comment by acpibob** [comment]
Perhaps a cast on "CurrentSp" might help?

**Comment by acpibob** [comment]
we have a debugger command, "stat stack" that displays the maximum stack use during execution:

    case CMD_STAT_STACK:
#if defined(ACPI_DEBUG_OUTPUT)

        Temp = (UINT32) ACPI_PTR_DIFF (
            AcpiGbl_EntryStackPointer, AcpiGbl_LowestStackPointer);

        AcpiOsPrintf ("\nSubsystem Stack Usage:\n\n");
        AcpiOsPrintf ("Entry Stack Pointer          %p\n", AcpiGbl_EntryStackPointer);
        AcpiOsPrintf ("Lowest Stack Pointer         %p\n", AcpiGbl_LowestStackPointer);
        AcpiOsPrintf ("Stack Use                    %X (%u)\n", Temp, Temp);
        AcpiOsPrintf ("Deepest Procedure Nesting    %u\n", AcpiGbl_DeepestNesting);
#endif
        break;

**Comment by wblaszcz** [comment]
export CFLAGS="-Wno-dangling-pointer" as a work around?

**Comment by t-8ch** [comment]
Making `AcpiGbl_EntryStackPointer` an `uintptr_t` should fix it.
However at the moment `ACPI_UINTPTR_T` is a `void *` for non-kernel linux builds, so this maybe would need to change.
