### ISSUE TITLE
-Werror makes it difficult for distro maintainers to build with newer GCC

### ISSUE THREAD

**Issue by valentindavid** [acpica/acpica#798]
I see that `generate/unix/Makefile.config` has `-Werror` in it. `-Werror` is a great development tool. But it breaks builds with newer versions of GCC. To help distro maintainers, I recommend you make it optional. Otherwise we have to patch it away. Or we can never update GCC. Thank you.

**Comment by acpibob** [comment]
Just what do you mean by “breaks builds”? (i.e., just what breaks?)


From: Valentin David ***@***.***>
Sent: Tuesday, September 27, 2022 12:44 PM
To: acpica/acpica ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [acpica/acpica] -Werror makes it difficult for distro maintainers to build with newer GCC (Issue #798)


I see that generate/unix/Makefile.config has -Werror in it. -Werror is a great development tool. But it breaks builds with newer versions of GCC. To help distro maintainers, I recommend you make it optional. Otherwise we have to patch it away. Or we can never update GCC. Thank you.

**Comment by valentindavid** [comment]
For instance, with GCC 12.2.0, we get:

```
../../../source/components/utilities/utdebug.c: In function ‘AcpiUtInitStackPtrTrace’:
../../../source/components/utilities/utdebug.c:188:31: error: storing the address of local variable ‘CurrentSp’ in ‘AcpiGbl_EntryStackPointer’ [-Werror=dangling-pointer=]
  188 |     AcpiGbl_EntryStackPointer = &CurrentSp;
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
../../../source/components/utilities/utdebug.c:185:29: note: ‘CurrentSp’ declared here
  185 |     ACPI_SIZE               CurrentSp;
      |                             ^~~~~~~~~
In file included from ../../../source/include/acpi.h:173,
                 from ../../../source/components/utilities/utdebug.c:154:
../../../source/include/acglobal.h:334:41: note: ‘AcpiGbl_EntryStackPointer’ declared here
  334 | ACPI_GLOBAL (ACPI_SIZE *,               AcpiGbl_EntryStackPointer);
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~
../../../source/include/acpixf.h:188:17: note: in definition of macro ‘ACPI_GLOBAL’
  188 |     extern type name
```

**Comment by acpibob** [comment]
I think we have fixes for these already, they will appear in the next release of ACPICA.

**Comment by valentindavid** [comment]
This is not the point of the issue. It is a long term maintenance issue for distros. Sorry for being annoying.

It is totally fine if the default behavior is to have `-Werror`. But we would prefer a way to disable it by passing a variable to make instead of patching it.

Would you like me to submit a patch?

**Comment by acpibob** [comment]
I don’t understand why GCC has to change so much. We encounter problems like this for just about every release of GCC.

Yes, please submit a pull request with the patch.
Thanks,
Bob
