### ISSUE TITLE
acpica-unix-20240827 missing "acpixf.h" but has "ACPIXF.H"

### ISSUE THREAD

**Issue by cfconrad** [acpica/acpica#971]
Hi,
it looks like the file ["acpixf.h" ](https://github.com/acpica/acpica/blob/86c762a/source/include/acpixf.h) is placed in uppercase letters in https://github.com/user-attachments/files/16769900/acpica-unix-20240827.tar.gz .

At least for me I get a compile error like:
```
../../../source/include/acpi.h:173:10: fatal error: acpixf.h: No such file or directory
 #include "acpixf.h"             /* ACPI core subsystem external interfaces */
          ^~~~~~~~~~
```

see:
```
$ wget -q https://github.com/user-attachments/files/16769900/acpica-unix-20240827.tar.gz -O - | tar -ztvf - | grep -i acpixf.h
-rwx------ sdumbre/Domain Users  42321 2024-08-27 23:14 acpica-unix-20240827/source/include/ACPIXF.H
```

**Comment by ElyesH** [comment]
Hi,

I’m experiencing the same issue.
 
@sacdintel , are you using only windows to check & validate the build process?

Please note that on Linux and BSD systems, the files "acpixf.h" and "ACPIXF.H" are treated as different due to case sensitivity in their file systems.

Would it be possible to push a new release addressing this(all known) issue(s)?

**Comment by chenrui333** [comment]
I am seeing the same issue while building 20240827 for homebrew on linux, https://github.com/Homebrew/homebrew-core/pull/183439

**Comment by sacdintel** [comment]
I apologize for the capitalized filename which was pushed from my MSVC for some reason (possibly an MSVC bug?) and I see that now. When it comes to the release, would just replacing the file work and then doing the build process again or do I need to do something more? I think the Windows executables should work just fine, but I can rebuild everything and reupload the whole release. Just note that the date on the release will change to the date when I actually run the build again and also a handful of commits that I have since merged will be part of the new release but it will take about 2 weeks or so for the whole release to be done and updated on the website, thanks.

**Comment by sacdintel** [comment]
[acpixf.zip](https://github.com/user-attachments/files/17170064/acpixf.zip)


Here is the .zip containing acpixf.h for the release 20240827, sorry about that. Thanks a lot!

**Comment by ElyesH** [comment]
Hi,
The acpica.org page is not updated 
we can't download the latest release
Thx

**Comment by sacdintel** [comment]
Hi @ElyesH ,

The new release is currently being worked on by the website maintainers and we should have it available by Monday at the latest (from what I was told). It usually takes about 1-2 weeks more for the website to be updated now that it was forced to be moved to an Intel Developers Zone webpage. Thanks!

**Comment by SaketADumbre** [comment]
I believe this issue has been resolved, so can I go ahead and close this issue? I am sorry once again about the mistakes occurring from my end, I will make sure to adapt my best practices to ensure I don't repeat such mistakes. Thank you very much for your patience!

**Comment by cfconrad** [comment]
Thanks a lot for taking action. Yes we can close the issue.
